import { isCommonPassword } from "./commonPasswords.js";
import { estimateEntropy } from "./entropyEstimator.js";
import { detectPatterns } from "./patternDetector.js";

function analyzeLength(length) {
  if (length === 0) return { value: 0, rating: "empty", message: "No password was provided." };
  if (length < 8) return { value: length, rating: "very-short", message: "Short passwords leave fewer guesses for an attacker." };
  if (length < 12) return { value: length, rating: "short", message: "Longer passwords generally provide more search space." };
  if (length < 16) return { value: length, rating: "moderate", message: "The length is a reasonable starting point." };
  return { value: length, rating: "long", message: "The length contributes meaningful theoretical search space." };
}

function analyzeComposition(password) {
  const characters = Array.from(password);
  const composition = {
    lowercase: /[a-z]/.test(password),
    uppercase: /[A-Z]/.test(password),
    digits: /[0-9]/.test(password),
    symbols: /[^a-zA-Z0-9]/.test(password),
    uniqueCharacters: new Set(characters).size,
  };
  composition.characterSetCount = [composition.lowercase, composition.uppercase, composition.digits, composition.symbols]
    .filter(Boolean).length;
  composition.repetitionRatio = characters.length === 0 ? 0 : Number((1 - composition.uniqueCharacters / characters.length).toFixed(2));
  return composition;
}

function buildWarnings(password, commonPassword, patterns, length, composition) {
  const warnings = [];
  if (commonPassword) warnings.push("This password matches a locally known common password.");
  if (length.value > 0 && length.value < 12) warnings.push("Consider using at least 12 characters.");
  if (composition.characterSetCount < 2 && password.length > 0) warnings.push("The password uses only one character category.");
  if (composition.repetitionRatio >= 0.5) warnings.push("A large portion of the password is repeated.");
  for (const finding of patterns) warnings.push(finding.explanation);
  return [...new Set(warnings)];
}

function buildRecommendations(commonPassword, patterns, length, composition) {
  const recommendations = [];
  if (commonPassword) recommendations.push("Replace it with a unique password generated by a password manager.");
  if (length.value < 12) recommendations.push("Increase the length before relying on character variety.");
  if (composition.characterSetCount < 3) recommendations.push("Use a longer random password or a multi-word passphrase.");
  if (patterns.length > 0) recommendations.push("Remove predictable sequences, repeated blocks, dates, and common word patterns.");
  if (recommendations.length === 0) recommendations.push("Use this value only once and store it in a reputable password manager.");
  return [...new Set(recommendations)];
}

function calculateScore(password, length, entropy, commonPassword, patterns, composition) {
  if (!password) return 0;
  let score = 45;
  if (length.value >= 16) score += 20;
  else if (length.value >= 12) score += 12;
  else if (length.value >= 8) score += 2;
  else score -= 20;
  score += Math.min(composition.characterSetCount * 5, 20);
  score += Math.min(Math.floor(entropy.bits / 20), 15);
  if (composition.repetitionRatio >= 0.5) score -= 20;
  else if (composition.repetitionRatio >= 0.25) score -= 8;
  if (commonPassword) score -= 55;
  score -= Math.min(patterns.reduce((total, finding) => total + (finding.risk === "high" ? 15 : 7), 0), 45);
  return Math.max(0, Math.min(100, score));
}

function strengthForScore(score) {
  if (score < 25) return "Very weak";
  if (score < 45) return "Weak";
  if (score < 65) return "Fair";
  if (score < 85) return "Strong";
  return "Very strong";
}

export function analyzePassword(password) {
  const value = typeof password === "string" ? password : "";
  const length = analyzeLength(Array.from(value).length);
  const characterSets = analyzeComposition(value);
  const entropy = estimateEntropy(value);
  const commonPassword = isCommonPassword(value);
  const patterns = detectPatterns(value);
  const score = calculateScore(value, length, entropy, commonPassword, patterns, characterSets);

  return {
    score,
    strength: strengthForScore(score),
    length,
    entropy,
    characterSets,
    commonPassword: { detected: commonPassword },
    patterns,
    predictabilityIndicators: patterns.map(({ type, risk }) => ({ type, risk })),
    warnings: buildWarnings(value, commonPassword, patterns, length, characterSets),
    recommendations: buildRecommendations(commonPassword, patterns, length, characterSets),
  };
}